version: '3.1'

services:
  odoo:
    image: odoo:17.0
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./src:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
